package: 
  name: plasma_math_tools
  version: 1.0.12

source:
  git_rev: 1.0.12
  git_url: https://github.com/AreWeDreaming/plasma_math_tools

requirements:
  build:
    - python >=3.7
    - pip >=21.0
    - setuptools >=57.4
    - build >=0.7

  run:
    - python >=3.7
    - matplotlib >=3.3
    - numpy >=1.21
    - scipy >=1.7

test:
  imports:
    - unittest

about:
  home: