package: 
  name: plasma_math_tools
  version: 1.0.2

source:
  git_rev: 1.0.2
  git_url: https://github.com/AreWeDreaming/plasma_math_tools

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib >=3.3.4
    - numpy >=1.21.4 
    - scipy >=1.7.3

test:
  imports:
    - unittest

about:
  home: