package: 
  name: plasma_math_tools
  version: 1.0.2

source:
  git_rev: 1.0.2
  git_url: https://github.com/AreWeDreaming/plasma_math_tools

requirements:
  build:
    - python >=3.7.10
    - setuptools >=57.4.0
    - build >=0.8.0

  run:
    - pythonv>=3.7.10
    - matplotlib >=3.3.4
    - numpy >=1.21.4 
    - scipy >=1.7.3

test:
  imports:
    - unittest

about:
  home: