context: {}
package:

  name: plasma_math_tools
  version: 1.0.19

source:
  git_rev: 1.0.19
  git_url: https://github.com/AreWeDreaming/plasma_math_tools

build:
    number: 1

requirements:
  build:
    - python
    - pip >=21.0
    - setuptools >=57.4
    - build >=0.7

  run:
    - python
    - matplotlib >=3.3
    - numpy >=1.21
    - scipy >=1.7


